/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectolaberinto.view;

/**
 *
 * @author Yuliana
 */
public class GUIHistory extends javax.swing.JFrame {

    /**
     * Creates new form GUIHistory
     */
    public GUIHistory() {
        initComponents();
    }
    
    public PanelHistory getPanelHistory(){
        return this.panelHistory1;
    }
    
    public PanelHistoryButton getPanelHistoryButton(){
        return this.panelHistoryButton1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHistory1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelHistory();
        panelHistoryButton1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelHistoryButton();
        txtBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(705, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        panelHistory1.setMinimumSize(new java.awt.Dimension(739, 158));
        getContentPane().add(panelHistory1);
        panelHistory1.setBounds(190, 30, 430, 340);
        getContentPane().add(panelHistoryButton1);
        panelHistoryButton1.setBounds(48, 40, 100, 44);

        txtBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InstruccionesYHistoria.jpg"))); // NOI18N
        txtBackground.setMaximumSize(new java.awt.Dimension(705, 470));
        txtBackground.setMinimumSize(new java.awt.Dimension(705, 470));
        txtBackground.setPreferredSize(new java.awt.Dimension(705, 470));
        txtBackground.setRequestFocusEnabled(false);
        getContentPane().add(txtBackground);
        txtBackground.setBounds(-10, -15, 700, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelHistory panelHistory1;
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelHistoryButton panelHistoryButton1;
    private javax.swing.JLabel txtBackground;
    // End of variables declaration//GEN-END:variables
}
