/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectolaberinto.view;

/**
 *
 * @author Yuliana
 */
public class GUIInformation extends javax.swing.JFrame {

    /**
     * Creates new form GUIInformation
     */
    public GUIInformation() {
        initComponents();
    }

    public PanelInformationGame getPanelInformation() {
        return this.panelInformationGame1;
    }

    public PanelButtonInformation getPanelButtonInformation() {
        return this.panelButtonInformation1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformationGame1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelInformationGame();
        panelButtonInformation1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonInformation();
        txtBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(705, 470));
        getContentPane().setLayout(null);
        getContentPane().add(panelInformationGame1);
        panelInformationGame1.setBounds(200, 40, 410, 250);
        getContentPane().add(panelButtonInformation1);
        panelButtonInformation1.setBounds(520, 330, 93, 55);

        txtBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InstruccionesYHistoria.jpg"))); // NOI18N
        txtBackground.setPreferredSize(new java.awt.Dimension(705, 470));
        getContentPane().add(txtBackground);
        txtBackground.setBounds(-2, -17, 710, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonInformation panelButtonInformation1;
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelInformationGame panelInformationGame1;
    private javax.swing.JLabel txtBackground;
    // End of variables declaration//GEN-END:variables
}
