/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectolaberinto.view;

import java.awt.event.KeyListener;

/**
 *
 * @author Yuliana
 */
public class GUIPlayGame extends javax.swing.JFrame {
    // private final ImageIcon imagePanelPlay = new ImageIcon("DibujoCamino.png");

    /**
     * Creates new form GUIPlayGame
     */
    public GUIPlayGame() {
        initComponents();
    }


    public PanelGame getPanelGame1() {
        return panelGame1;
    }
    
    public PanelButtonPlayGame getPanelButtonPlayGame(){
        return panelButtonPlayGame1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlayText1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelPlayScore();
        panelGame1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelGame();
        panelButtonPlayGame1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonPlayGame();
        txtManzana1 = new javax.swing.JLabel();
        txtManzana2 = new javax.swing.JLabel();
        txtManzana3 = new javax.swing.JLabel();
        txtManzana4 = new javax.swing.JLabel();
        txtManzana5 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(panelPlayText1);
        panelPlayText1.setBounds(620, 240, 150, 50);

        panelGame1.setMinimumSize(new java.awt.Dimension(550, 550));
        panelGame1.setPreferredSize(new java.awt.Dimension(550, 550));

        javax.swing.GroupLayout panelGame1Layout = new javax.swing.GroupLayout(panelGame1);
        panelGame1.setLayout(panelGame1Layout);
        panelGame1Layout.setHorizontalGroup(
            panelGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        panelGame1Layout.setVerticalGroup(
            panelGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(panelGame1);
        panelGame1.setBounds(20, 20, 550, 550);

        panelButtonPlayGame1.setFocusable(false);
        getContentPane().add(panelButtonPlayGame1);
        panelButtonPlayGame1.setBounds(640, 530, 119, 46);

        txtManzana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manzanas.png"))); // NOI18N
        getContentPane().add(txtManzana1);
        txtManzana1.setBounds(590, 180, 40, 50);

        txtManzana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manzanas.png"))); // NOI18N
        getContentPane().add(txtManzana2);
        txtManzana2.setBounds(630, 180, 40, 50);

        txtManzana3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manzanas.png"))); // NOI18N
        getContentPane().add(txtManzana3);
        txtManzana3.setBounds(670, 180, 40, 50);

        txtManzana4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manzanas.png"))); // NOI18N
        getContentPane().add(txtManzana4);
        txtManzana4.setBounds(710, 180, 40, 50);

        txtManzana5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manzanas.png"))); // NOI18N
        getContentPane().add(txtManzana5);
        txtManzana5.setBounds(750, 180, 40, 50);

        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoInterfaz.png"))); // NOI18N
        getContentPane().add(txtImagen);
        txtImagen.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonPlayGame panelButtonPlayGame1;
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelGame panelGame1;
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelPlayScore panelPlayText1;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JLabel txtManzana1;
    private javax.swing.JLabel txtManzana2;
    private javax.swing.JLabel txtManzana3;
    private javax.swing.JLabel txtManzana4;
    private javax.swing.JLabel txtManzana5;
    // End of variables declaration//GEN-END:variables
}
