/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectolaberinto.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Yuliana
 */
public class GUIStartGame extends javax.swing.JFrame {

   

    /**
     * Creates new form StartGameFrame
     */
    public GUIStartGame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButtonStart1 = new ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonStart();
        txtBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 490));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(panelButtonStart1);
        panelButtonStart1.setBounds(140, 80, 430, 312);

        txtBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazPrincipal.jpg"))); // NOI18N
        txtBackground.setText("jLabel1");
        getContentPane().add(txtBackground);
        txtBackground.setBounds(0, 0, 670, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    public PanelButtonStart getPanelButtonsStart() {
        return this.panelButtonStart1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.tm2100.g3.proyectolaberinto.view.PanelButtonStart panelButtonStart1;
    private javax.swing.JLabel txtBackground;
    // End of variables declaration//GEN-END:variables
}
