/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectolaberinto.view;

/**
 *
 * @author Yuliana
 */
public class PanelHistory extends javax.swing.JPanel {

    /**
     * Creates new form PanelHistory
     */
    public PanelHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTítulo = new javax.swing.JLabel();
        txtHistoria1 = new javax.swing.JLabel();
        txtHistoria2 = new javax.swing.JLabel();
        jLabeltxtHistoria3 = new javax.swing.JLabel();
        txtHistoria4 = new javax.swing.JLabel();
        txtHistoria5 = new javax.swing.JLabel();
        txtHistoria6 = new javax.swing.JLabel();
        txtHistoria7 = new javax.swing.JLabel();
        txtHistoria8 = new javax.swing.JLabel();
        txtHistoria9 = new javax.swing.JLabel();
        txtHistoria10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(111, 191, 126));

        txtTítulo.setFont(new java.awt.Font("Comic Sans MS", 0, 23)); // NOI18N
        txtTítulo.setText("Historia del juego");

        txtHistoria1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria1.setText("En el colorido mundo de “Squark y la Bolsa Perdida”, los jugadores");

        txtHistoria2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria2.setText("los jugadores siguen a Squark, un intrépido honguito que ha");

        jLabeltxtHistoria3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeltxtHistoria3.setText("perdido su valiosa bolsa de legumbres, esencial para mantener el");

        txtHistoria4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria4.setText("para mantener el equilibrio saludable de su mundo. Sin ella, el");

        txtHistoria5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria5.setText("reino ha sido invadido por malvados enemigos: la comida chatarra.");

        txtHistoria6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria6.setText("Squark se aventura en un peligroso laberinto lleno de trampas y  ");

        txtHistoria7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria7.setText("villanos, desde pizzas hasta papas fritas, que intentan detenerlo.  ");

        txtHistoria8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria8.setText("Usando su ingenio y habilidades, Squark deberá enfrentarse a estos ");

        txtHistoria9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria9.setText(" enemigos para recuperar la bolsa perdida y restaurar la salud en su ");

        txtHistoria10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHistoria10.setText("mundo.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria2))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltxtHistoria3))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria5))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(txtTítulo))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria7))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria8))
            .addComponent(txtHistoria9)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoria10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTítulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltxtHistoria3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria5)
                .addGap(29, 29, 29)
                .addComponent(txtHistoria6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoria10)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeltxtHistoria3;
    private javax.swing.JLabel txtHistoria1;
    private javax.swing.JLabel txtHistoria10;
    private javax.swing.JLabel txtHistoria2;
    private javax.swing.JLabel txtHistoria4;
    private javax.swing.JLabel txtHistoria5;
    private javax.swing.JLabel txtHistoria6;
    private javax.swing.JLabel txtHistoria7;
    private javax.swing.JLabel txtHistoria8;
    private javax.swing.JLabel txtHistoria9;
    private javax.swing.JLabel txtTítulo;
    // End of variables declaration//GEN-END:variables
}
